In [99]:
import numpy as np
arr = np.array([1,5,2,9,10])
arr

array([ 1,  5,  2,  9, 10])

In [100]:
# функция np.array возвращает объекты типа numpy.ndarray:
print(type(arr))

<class 'numpy.ndarray'>


In [101]:
#двумерный массив из списка списков
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ])
nd_arr

array([[12, 45, 78],
       [34, 56, 13],
       [12, 98, 76]])

In [102]:
#Какого типа данные хранятся теперь в массиве ar
arr = np.array([1,5,2,9,10])
arr.dtype

dtype('int64')

In [103]:
#Задать тип данных сразу при создании массива можно 
# с помощью  dtype:
arr = np.array([1,5,2,9,10], dtype=np.int8)
arr

array([ 1,  5,  2,  9, 10], dtype=int8)

In [104]:
#если добавить в arr число больше 127 или меньше -128, оно потеряет 
# исходное значение
arr[2] = 2000
arr

/var/folders/xk/63qzhfp52rzctyyxh6mgn8rw0000gn/T/ipykernel_15659/1941816533.py:3: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 2000 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  arr[2] = 2000


array([  1,   5, -48,   9,  10], dtype=int8)

In [105]:
#Если добавить float в массив int, пропадёт десятичная часть
arr[2] = 125.5
arr

array([  1,   5, 125,   9,  10], dtype=int8)

In [106]:
#Строка-число будет приведена к нужному типу автоматически, 
#для иных строк возникнет ошибка
arr[2] = '12'
arr

array([ 1,  5, 12,  9, 10], dtype=int8)

In [107]:
#Поменять тип данных во всём массиве:
arr = np.float128(arr)
arr

AttributeError: module 'numpy' has no attribute 'float128'

In [ ]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)

In [ ]:
#Узнать размерность массива
print(arr.ndim)
print(nd_arr.ndim)

1
2


In [ ]:
#Узнать общее число элементов в массиве
print(arr.size)
nd_arr.size

5


9

In [ ]:
#Форма или структура массива 
print(arr.shape)
nd_arr.shape


(5,)


(3, 3)

Форма массива хранится в виде кортежа с числом элементов, равным размерности массива. Соответственно, для одномерного массива напечатан кортеж длины 1. 

узнать, сколько «весит» каждый элемент массива в байтах 

In [ ]:
arr.itemsize
# 1
nd_arr.itemsize

2

одномерный массив из пяти нулей

In [ ]:
zeros_1d = np.zeros(5)
zeros_1d

array([0., 0., 0., 0., 0.])

трёхмерный массив с формой 5x4x3 и типом float32

In [ ]:
zeros_3d = np.zeros((5,4,3), dtype=np.float32)
print(zeros_3d.shape)

(5, 4, 3)


В отличие от range, в функции arange все перечисленные параметры могут иметь тип float.

In [ ]:
np.arange(2.5, 5)

array([2.5, 3.5, 4.5])

массив от 2.5 до 5 с шагом 0.5

In [ ]:
np.arange(2.5, 5, 0.5)

array([2.5, 3. , 3.5, 4. , 4.5])

массив от 2.5 до 5 с шагом 0.5 и с типом float16:

In [ ]:
np.arange(2.5, 5, 0.5, dtype=np.float16)

array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

операции с плавающей точкой не всегда бывают предсказуемыми из-за особенностей хранения таких чисел в памяти компьютера. Для работы с дробными параметрами start, stop и step лучше использовать функцию linspace. Она тоже возвращает одномерный массив из чисел, расположенных на равном удалении друг от друга между началом и концом диапазона, но обладает немного другим поведением и сигнатурой:

np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

start и stop являются обязательными параметрами, задающими начало и конец возвращаемого диапазона;
num — параметр, задающий число элементов, которое должно оказаться в массиве (по умолчанию 50);
endpoint — включён или исключён конец диапазона (по умолчанию включён);
retstep (по умолчанию False) позволяет указать, возвращать ли использованный шаг между значениями, помимо самого массива;
dtype — уже хорошо знакомый нам параметр, задающий тип данных (если не задан, определяется автоматически).

массив из десяти чисел между 1 и 2

In [ ]:
arr = np.linspace(1, 2, 10)
arr

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

массив из десяти чисел между 1 и 2, не включая 2(endpoint=False)

In [ ]:
arr = np.linspace(1, 2, 10, endpoint=False)
arr

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

какой шаг был использован для создания массива из десяти чисел между 1 и 2, где 2 включалось и не включалось

In [ ]:
arr, step = np.linspace(1, 2, 10, endpoint=True, retstep=True)
print(step)

arr, step = np.linspace(1, 2, 10, endpoint=False, retstep=True)
print(step)

0.1111111111111111
0.1


Задание 6.6
С каким шагом сгенерируется массив из 60 чисел от -6 до 21 включительно? 
Ответ округлите до двух знаков после точки.

In [ ]:
arr, step = np.linspace(-6, 21, 60, endpoint=True, retstep=True)
print(step)

0.4576271186440678


Задание 6.7

С каким шагом сгенерируется массив из 60 чисел от -6 (включительно) до 21 (не включительно)? Ответ округлите до 2 знаков после точки.

In [ ]:
arr, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
print(step)

0.45


Создадим массив из восьми чисел

In [ ]:
import numpy as np
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

Поменять форму массива arr можно с помощью присвоения атрибуту shape кортежа с желаемой формой:

In [ ]:
arr.shape = (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

Чтобы оставить исходный массив без изменений и дополнительно получить новый массив новой формы, нужно использовать функцию reshape

In [ ]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4))
arr_new

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

У функции reshape есть дополнительный именованный аргумент order. Он задаёт принцип, по которому элементы заполняют массив новой формы. Если order='C' (по умолчанию), массив заполняется по строкам, как в примере выше. Если order='F', массив заполняется числами по столбцам:

In [ ]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4), order='F')
arr_new

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

транспонирование. Эта операция меняет строки и столбцы массива местами. В NumPy эту операцию совершает функция transpose

In [ ]:
arr = np.arange(8)
arr.shape = (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
arr_trans = arr.transpose()
arr_trans

array([0, 1, 2, 3, 4, 5, 6, 7])